// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

import "@confluxfans/contracts/InternalContracts/PoSRegister.sol";

/**
* This is a fake empty contract for testing purpose.
*/ 
contract FakePoSRegister is PoSRegister {

  mapping(address => bytes32) private addressToIdentifierMap;
  mapping(bytes32 => address) private identifierToAddressMap;

  mapping(address => uint64) private userVotes;
  mapping(address => uint64) private userUnlockedVotes;

  function _addressToBytes(address a) public pure returns (bytes memory b){
    assembly {
        let m := mload(0x40)
        a := and(a, 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF)
        mstore(add(m, 20), xor(0x140000000000000000000000000000000000000000, a))
        mstore(0x40, add(m, 52))
        b := m
    }
  }

  /**
     * @dev Register PoS account
     * @param indentifier - PoS account address to register
     * @param votePower - votes count
     * @param blsPubKey - BLS public key
     * @param vrfPubKey - VRF public key
     * @param blsPubKeyProof - BLS public key's proof of legality, used to against some attack, generated by conflux-rust fullnode
     */
    function register(
        bytes32 indentifier,
        uint64 votePower,
        bytes calldata blsPubKey,
        bytes calldata vrfPubKey,
        bytes[2] calldata blsPubKeyProof
    ) external override {
      bytes32 _identifier = keccak256(_addressToBytes(msg.sender));
      addressToIdentifierMap[msg.sender] = _identifier;
      identifierToAddressMap[_identifier] = msg.sender;
      emit Register(_identifier, blsPubKey, vrfPubKey);
    }

    /**
     * @dev Increase specified number votes for msg.sender
     * @param votePower - count of votes to increase
     */
    function increaseStake(uint64 votePower) external override {
      userVotes[msg.sender] += votePower;
      emit IncreaseStake(addressToIdentifierMap[msg.sender], votePower);
    }

    /**
     * @dev Retire specified number votes for msg.sender
     * @param votePower - count of votes to retire
     */
    function retire(uint64 votePower) external override {
      // TODO add delay seven days logic
      userUnlockedVotes[msg.sender] += votePower;
      emit Retire(addressToIdentifierMap[msg.sender], votePower);
    }

    /**
     * @dev Query PoS account's lock info. Include "totalStakedVotes" and "totalUnlockedVotes"
     * @param identifier - PoS address
     */
    function getVotes(bytes32 identifier) external override view returns (uint256, uint256) {
      address _address = identifierToAddressMap[identifier];
      return (userVotes[_address], userUnlockedVotes[_address]);
    }

    /**
     * @dev Query the PoW address binding with specified PoS address
     * @param identifier - PoS address
     */
    function identifierToAddress(bytes32 identifier) external override view returns (address) {
      return identifierToAddressMap[identifier];
    }

    /**
     * @dev Query the PoS address binding with specified PoW address
     * @param addr - PoW address
     */
    function addressToIdentifier(address addr) external override view returns (bytes32) {
      return addressToIdentifierMap[addr];
    }
}
